
# NumPy Practice Projects with Hints

This notebook contains 10 NumPy practice projects.

Rules:
- Try solving each problem yourself first.
- Use the hints only if you get stuck.
- Prefer NumPy vectorized operations over loops whenever possible.

Good luck 🚀


## 1. Student Marks Analyzer

Create a 2D NumPy array where:
- rows = students
- columns = subjects

Tasks:
- Find average marks per student
- Find highest scorer
- Find subject-wise averages
- Find failed students (<35)
- Find topper per subject


### Hints
- Use `np.mean(..., axis=?)`
- Use `np.max()` and `np.argmax()`
- Think carefully about `axis=0` vs `axis=1`
- Boolean filtering will help for failed students


In [2]:
# Write your solution here
import numpy as np
student_data=np.array([[1,90,80,90,80,80,99],[2,50,80,40,80,80,80],[3,50,20,90,80,40,90],[4,30,80,90,50,20,90],[5,10,40,50,20,11,70],[6,80,45,36,45,36,34],[7,66,84,45,57,26,46],[8,46,46,35,35,56,35]])
print(student_data)
print("student wise avg")
print(np.mean((student_data[:,1:]),axis=1))
print("top scorer")
a=(np.argmax(np.mean((student_data[:,1:]),axis=1)))
print(student_data[a,0])
print()
print("subject wise average")
print(np.mean(student_data[:,1:],axis=0))
print()
print("failed students")
print(student_data[np.mean((student_data[:,1:]),axis=1)<35])
print(np.mean((student_data[:,1:]),axis=1)<35)



[[ 1 90 80 90 80 80 99]
 [ 2 50 80 40 80 80 80]
 [ 3 50 20 90 80 40 90]
 [ 4 30 80 90 50 20 90]
 [ 5 10 40 50 20 11 70]
 [ 6 80 45 36 45 36 34]
 [ 7 66 84 45 57 26 46]
 [ 8 46 46 35 35 56 35]]
student wise avg
[86.5        68.33333333 61.66666667 60.         33.5        46.
 54.         42.16666667]
top scorer
1

subject wise average
[52.75  59.375 59.5   55.875 43.625 68.   ]

failed students
[[ 5 10 40 50 20 11 70]]
[False False False False  True False False False]


## 2. Weather Temperature Analysis

Generate random temperatures for 30 days.

Tasks:
- Find hottest and coldest day
- Find average temperature
- Find days above average
- Reshape into weekly data
- Find weekly averages


### Hints
- Use `np.random.randint()`
- Use `reshape()` for weekly grouping
- Use boolean indexing for above-average days
- `np.mean()` will help for averages


In [3]:
# Write your solution here

weather_data=np.random.randint(20,40,30)
max_temp=np.max(weather_data)
min_temp=np.min(weather_data)
avg_temp=np.mean(weather_data)
days_above_avg_temp=(weather_data>avg_temp)

print(weather_data[days_above_avg_temp])
weather_data=np.append(weather_data,[0,0,0,0,0])
weather_data=(weather_data.reshape(5,7))
weekly_avg= np.mean(weather_data[0:4,:])
print(weather_data)
print()

print(max_temp,min_temp)
print()
print(avg_temp)
print()
print(weekly_avg)
print()



[34 37 37 39 31 31 36 38 39 31 33 37 37 33 31 39]
[[34 37 37 24 29 39 20]
 [27 23 31 31 25 36 38]
 [39 21 31 24 33 29 28]
 [20 37 22 37 26 33 31]
 [22 39  0  0  0  0  0]]

39 20

30.1

30.071428571428573



## 3. Image Pixel Simulator

Create a random 256x256 grayscale image array.

Tasks:
- Increase brightness
- Decrease brightness
- Crop image
- Flip image horizontally
- Normalize pixel values


### Hints
- Pixel values are usually between 0–255
- Add/subtract values for brightness changes
- Use slicing for cropping
- Use `np.flip()` or slicing tricks
- Normalize using division


In [4]:
# Write your solution here
image = np.random.randint(0,255,size=(256,256))
print(image)
print("-------------------")
# increase bright ness
print(image+1)
print("-------------------")
# decrease bright ness 
print(image-1)
# cropping the image 
print("-------------------")
#cropping the image
print(image[250:,250:])
print("-------------------")
# flipping the image 
print(np.flip(image))
print("-------------------")
#normalizing the image 

print((image-np.min(image))/(np.max(image)-np.min(image)))





[[ 68 234 122 ... 214 224 206]
 [163 233 129 ...  72 150 216]
 [188 216  82 ... 240  38 247]
 ...
 [ 43 123 166 ... 116 116  59]
 [187 103 211 ...  11  17 121]
 [177  66 170 ...  71   6 172]]
-------------------
[[ 69 235 123 ... 215 225 207]
 [164 234 130 ...  73 151 217]
 [189 217  83 ... 241  39 248]
 ...
 [ 44 124 167 ... 117 117  60]
 [188 104 212 ...  12  18 122]
 [178  67 171 ...  72   7 173]]
-------------------
[[ 67 233 121 ... 213 223 205]
 [162 232 128 ...  71 149 215]
 [187 215  81 ... 239  37 246]
 ...
 [ 42 122 165 ... 115 115  58]
 [186 102 210 ...  10  16 120]
 [176  65 169 ...  70   5 171]]
-------------------
[[253 128  59  29 219 118]
 [112 118 204 229  81 121]
 [ 52 139 117 166 233 203]
 [ 11   2 243 116 116  59]
 [144   5  91  11  17 121]
 [169 250 221  71   6 172]]
-------------------
[[172   6  71 ... 170  66 177]
 [121  17  11 ... 211 103 187]
 [ 59 116 116 ... 166 123  43]
 ...
 [247  38 240 ...  82 216 188]
 [216 150  72 ... 129 233 163]
 [206 224 214 ... 122

## 4. Sales Data Dashboard

Create monthly sales data for multiple products.

Tasks:
- Total sales
- Best-selling product
- Monthly growth
- Highest sales month
- Cumulative sales


### Hints
- Use `axis` carefully
- Use `np.sum()`
- Use `np.cumsum()`
- Use subtraction to calculate growth


In [36]:
# Write your solution here
# the data is is 10X2  product id followed by sales 
products = np.arange(100,110).reshape(10,1)
sales = np.random.randint(10,432,size=(10,12)) 
data=np.concatenate((products,sales),axis=1) # data 
# print(data)

# product total sales 

total_sales_of_product= np.sum(data[:,1:],axis=1)
best_selling_product = np.argmax(np.sum(data[:,1:],axis=1))
print(total_sales_of_product)
print(data[best_selling_product,0:1])
monthly_wise_sales= np.sum(data[:,1:],axis=0)
print()
print(monthly_wise_sales)
best_selling_month=np.argmax(np.sum(data[:,1:],axis=0))
print(best_selling_month)
print()
month_wise_cum_data= np.cumsum(data[:,1:],axis=1)
print(month_wise_cum_data)


[2418 2833 3430 2367 2260 2847 2089 4036 1932 2066]
[107]

[2137 3036 1981 2092 2118 2646 2399 1940 1840 2112 1854 2123]
1

[[ 205  607  949 1083 1149 1503 1702 1898 1998 2183 2389 2418]
 [  46  406  483  800 1053 1461 1567 1852 1938 2260 2513 2833]
 [ 215  499  921 1229 1595 1898 2082 2206 2565 2877 3130 3430]
 [  76  314  448  650  908 1062 1342 1509 1610 1799 2161 2367]
 [ 343  639  735 1131 1236 1490 1770 1859 1987 2104 2193 2260]
 [  54  402  739  904 1256 1544 1777 1880 2039 2338 2435 2847]
 [ 345  600  612  758 1108 1300 1624 1673 1854 1905 1988 2089]
 [ 360  767  940 1227 1439 1840 2077 2460 2884 3247 3611 4036]
 [ 295  415  757  846  938 1043 1184 1557 1603 1653 1716 1932]
 [ 198  524  570  618  682  869 1284 1455 1711 1935 2019 2066]]


## 5. NumPy Mini Calculator

Create functions for:
- Matrix addition
- Matrix subtraction
- Matrix multiplication
- Transpose
- Determinant


### Hints
- Use `+`, `-`, `@`
- Use `.T` for transpose
- Use `np.linalg.det()`
- Remember matrix shapes must match


In [51]:
# Write your solution here
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
B= np.array([[1,1,1],[2,2,2],[3,3,3]])

print(A)
print()
print(B)

print(A+B)
print()
print(A-B)
print()
print(np.dot(A,B))
print()
print(np.transpose(A))

print()
print(np.linalg.det(A))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]

[[0 1 2]
 [2 3 4]
 [4 5 6]]

[[14 14 14]
 [32 32 32]
 [50 50 50]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

6.66133814775094e-16


## 6. Cricket Score Analyzer

Store runs scored by players across matches.

Tasks:
- Highest average
- Most consistent player
- Count 50+ scores
- Standard deviation of runs


### Hints
- Use `np.mean()`
- Use `np.std()`
- Boolean conditions help for 50+ scores
- Lower standard deviation means more consistency


In [95]:
# Write your solution here
players = np.arange(1,11).reshape(10,1)
scores = np.random.randint(1,121,(10,20))
data= np.concatenate((players,scores),axis=1)
print()
# print(data) 
print(data[np.argmax(np.mean(data[:,1:],axis=1),axis=0),:1])
# counting 50 + scores 
# print(data[:,1:][data[:,1:]>50])
print(np.sum(data[:,1:]>50,axis=1)) # 50+ scores of each player 
print(np.sum(data[:,1:]>50)) # total 50+ scores
std_dev_of_each_player=np.std(data[:,1:],axis=1)
print(data[np.argmin(std_dev_of_each_player),:1])








[6]
[ 7 11 10 13 12 15 10  9 14 11]
112
[8]


## 7. Recommendation System Mini Project

Create a user-movie rating matrix.

Tasks:
- Average movie rating
- Most liked movie
- Find similar users
- Recommend movies


### Hints
- Think of rows as users and columns as movies
- Use dot products for similarity
- Use averages across columns
- Broadcasting may help


In [8]:
# Write your solution here


## 8. NumPy Game of Life

Create a mini Conway's Game of Life.

Tasks:
- Create grid
- Count neighbors
- Update cells
- Simulate generations


### Hints
- Use a 2D array of 0s and 1s
- Slicing helps count neighbors
- Use conditions for alive/dead logic
- You may need nested loops initially


In [9]:
# Write your solution here


## 9. Fraud Detection Simulation

Generate transaction data.

Tasks:
- Detect abnormal transactions
- Find outliers using z-score
- Filter suspicious transactions


### Hints
- Use mean and standard deviation
- Z-score formula:
  z = (x - mean) / std
- Large absolute z-scores may indicate fraud


In [10]:
# Write your solution here


## 10. Mini Neural Network Forward Pass

Create:
- Input matrix
- Weight matrix
- Bias vector

Perform:
- Matrix multiplication
- Activation function
- Prediction output


### Hints
- Use `@` or `np.dot()`
- Use broadcasting for bias addition
- Try ReLU:
  `np.maximum(0, x)`
- Shape matching is very important


In [11]:
# Write your solution here
