
# NumPy Practice Projects with Hints

This notebook contains 10 NumPy practice projects.

Rules:
- Try solving each problem yourself first.
- Use the hints only if you get stuck.
- Prefer NumPy vectorized operations over loops whenever possible.

Good luck 🚀


## 1. Student Marks Analyzer

Create a 2D NumPy array where:
- rows = students
- columns = subjects

Tasks:
- Find average marks per student
- Find highest scorer
- Find subject-wise averages
- Find failed students (<35)
- Find topper per subject


### Hints
- Use `np.mean(..., axis=?)`
- Use `np.max()` and `np.argmax()`
- Think carefully about `axis=0` vs `axis=1`
- Boolean filtering will help for failed students


In [60]:
# Write your solution here
import numpy as np
student_data=np.array([[1,90,80,90,80,80,99],[2,50,80,40,80,80,80],[3,50,20,90,80,40,90],[4,30,80,90,50,20,90],[5,10,40,50,20,11,70],[6,80,45,36,45,36,34],[7,66,84,45,57,26,46],[8,46,46,35,35,56,35]])
print(student_data)
print("student wise avg")
print(np.mean((student_data[:,1:]),axis=1))
print("top scorer")
a=(np.argmax(np.mean((student_data[:,1:]),axis=1)))
print(student_data[a,0])
print()
print("subject wise average")
print(np.mean(student_data[:,1:],axis=0))
print()
print("failed students")
print(student_data[np.mean((student_data[:,1:]),axis=1)<35])
print(np.mean((student_data[:,1:]),axis=1)<35)



[[ 1 90 80 90 80 80 99]
 [ 2 50 80 40 80 80 80]
 [ 3 50 20 90 80 40 90]
 [ 4 30 80 90 50 20 90]
 [ 5 10 40 50 20 11 70]
 [ 6 80 45 36 45 36 34]
 [ 7 66 84 45 57 26 46]
 [ 8 46 46 35 35 56 35]]
student wise avg
[86.5        68.33333333 61.66666667 60.         33.5        46.
 54.         42.16666667]
top scorer
1

subject wise average
[52.75  59.375 59.5   55.875 43.625 68.   ]

failed students
[[ 5 10 40 50 20 11 70]]
[False False False False  True False False False]


## 2. Weather Temperature Analysis

Generate random temperatures for 30 days.

Tasks:
- Find hottest and coldest day
- Find average temperature
- Find days above average
- Reshape into weekly data
- Find weekly averages


### Hints
- Use `np.random.randint()`
- Use `reshape()` for weekly grouping
- Use boolean indexing for above-average days
- `np.mean()` will help for averages


In [127]:
# Write your solution here

weather_data=np.random.randint(20,40,30)
max_temp=np.max(weather_data)
min_temp=np.min(weather_data)
avg_temp=np.mean(weather_data)
days_above_avg_temp=(weather_data>avg_temp)

print(weather_data[days_above_avg_temp])
weather_data=np.append(weather_data,[0,0,0,0,0])
weather_data=(weather_data.reshape(5,7))
weekly_avg= np.mean(weather_data[0:4,:])
print(weather_data)
print()

print(max_temp,min_temp)
print()
print(avg_temp)
print()
print(weekly_avg)
print()



[35 39 31 35 37 37 32 34 37 35 34 34 30 37 34]
[[25 35 39 27 24 20 23]
 [20 31 35 24 20 28 37]
 [23 37 20 32 24 34 37]
 [35 23 34 34 24 26 30]
 [37 34  0  0  0  0  0]]

39 20

29.066666666666666

28.607142857142858



## 3. Image Pixel Simulator

Create a random 256x256 grayscale image array.

Tasks:
- Increase brightness
- Decrease brightness
- Crop image
- Flip image horizontally
- Normalize pixel values


### Hints
- Pixel values are usually between 0–255
- Add/subtract values for brightness changes
- Use slicing for cropping
- Use `np.flip()` or slicing tricks
- Normalize using division


In [137]:
# Write your solution here
image = np.random.randint(0,255,size=(256,256))
print(image)
print("-------------------")
# increase bright ness
print(image+1)
print("-------------------")
# decrease bright ness 
print(image-1)
# cropping the image 
print("-------------------")
#cropping the image
print(image[250:,250:])
print("-------------------")
# flipping the image 
print(np.flip(image))
print("-------------------")
#normalizing the image 

print((image-np.min(image))/(np.max(image)-np.min(image)))





[[108 172  86 ... 188 136 215]
 [199  81 206 ...  93 196  74]
 [ 34 220 191 ... 163 199 129]
 ...
 [182  49  65 ... 152 174 177]
 [118 131 172 ... 141 234 225]
 [199  56 192 ... 211  32   7]]
-------------------
[[109 173  87 ... 189 137 216]
 [200  82 207 ...  94 197  75]
 [ 35 221 192 ... 164 200 130]
 ...
 [183  50  66 ... 153 175 178]
 [119 132 173 ... 142 235 226]
 [200  57 193 ... 212  33   8]]
-------------------
[[107 171  85 ... 187 135 214]
 [198  80 205 ...  92 195  73]
 [ 33 219 190 ... 162 198 128]
 ...
 [181  48  64 ... 151 173 176]
 [117 130 171 ... 140 233 224]
 [198  55 191 ... 210  31   6]]
-------------------
[[170 130  34 234   6 236]
 [251 203 230 238 136  65]
 [ 12 160 143  81  41 124]
 [109  79  71 152 174 177]
 [ 82 187  39 141 234 225]
 [ 68 166  50 211  32   7]]
-------------------
[[  7  32 211 ... 192  56 199]
 [225 234 141 ... 172 131 118]
 [177 174 152 ...  65  49 182]
 ...
 [129 199 163 ... 191 220  34]
 [ 74 196  93 ... 206  81 199]
 [215 136 188 ...  86

## 4. Sales Data Dashboard

Create monthly sales data for multiple products.

Tasks:
- Total sales
- Best-selling product
- Monthly growth
- Highest sales month
- Cumulative sales


### Hints
- Use `axis` carefully
- Use `np.sum()`
- Use `np.cumsum()`
- Use subtraction to calculate growth


In [186]:
# Write your solution here
# the data is is 10X2  product id followed by sales 
products = np.arange(100,110).reshape(10,1)
sales = np.random.randint(10,432,size=(10,30))
data=np.concatenate((products,sales),axis=1)
# print(data)
print()
monthly_sales = np.sum(data[0:,1:],axis=1)
print(data[np.argmax(monthly_sales),0])
print()
print()
highest_sales_month= np.sum(data[:,1:],axis=1)
print(highest_sales_month)







100


[8040 6403 5863 7015 6379 6825 6537 6652 6364 7550]


## 5. NumPy Mini Calculator

Create functions for:
- Matrix addition
- Matrix subtraction
- Matrix multiplication
- Transpose
- Determinant


### Hints
- Use `+`, `-`, `@`
- Use `.T` for transpose
- Use `np.linalg.det()`
- Remember matrix shapes must match


In [ ]:
# Write your solution here


## 6. Cricket Score Analyzer

Store runs scored by players across matches.

Tasks:
- Highest average
- Most consistent player
- Count 50+ scores
- Standard deviation of runs


### Hints
- Use `np.mean()`
- Use `np.std()`
- Boolean conditions help for 50+ scores
- Lower standard deviation means more consistency


In [ ]:
# Write your solution here


## 7. Recommendation System Mini Project

Create a user-movie rating matrix.

Tasks:
- Average movie rating
- Most liked movie
- Find similar users
- Recommend movies


### Hints
- Think of rows as users and columns as movies
- Use dot products for similarity
- Use averages across columns
- Broadcasting may help


In [ ]:
# Write your solution here


## 8. NumPy Game of Life

Create a mini Conway's Game of Life.

Tasks:
- Create grid
- Count neighbors
- Update cells
- Simulate generations


### Hints
- Use a 2D array of 0s and 1s
- Slicing helps count neighbors
- Use conditions for alive/dead logic
- You may need nested loops initially


In [ ]:
# Write your solution here


## 9. Fraud Detection Simulation

Generate transaction data.

Tasks:
- Detect abnormal transactions
- Find outliers using z-score
- Filter suspicious transactions


### Hints
- Use mean and standard deviation
- Z-score formula:
  z = (x - mean) / std
- Large absolute z-scores may indicate fraud


In [ ]:
# Write your solution here


## 10. Mini Neural Network Forward Pass

Create:
- Input matrix
- Weight matrix
- Bias vector

Perform:
- Matrix multiplication
- Activation function
- Prediction output


### Hints
- Use `@` or `np.dot()`
- Use broadcasting for bias addition
- Try ReLU:
  `np.maximum(0, x)`
- Shape matching is very important


In [ ]:
# Write your solution here
