
# NumPy Practice Projects with Hints

This notebook contains 10 NumPy practice projects.

Rules:
- Try solving each problem yourself first.
- Use the hints only if you get stuck.
- Prefer NumPy vectorized operations over loops whenever possible.

Good luck 🚀


## 1. Student Marks Analyzer

Create a 2D NumPy array where:
- rows = students
- columns = subjects

Tasks:
- Find average marks per student
- Find highest scorer
- Find subject-wise averages
- Find failed students (<35)
- Find topper per subject


### Hints
- Use `np.mean(..., axis=?)`
- Use `np.max()` and `np.argmax()`
- Think carefully about `axis=0` vs `axis=1`
- Boolean filtering will help for failed students


In [4]:
# Write your solution here
import numpy as np
student_data=np.array([[1,90,80,90,80,80,99],[2,50,80,40,80,80,80],[3,50,20,90,80,40,90],[4,30,80,90,50,20,90],[5,10,40,50,20,11,70],[6,80,45,36,45,36,34],[7,66,84,45,57,26,46],[8,46,46,35,35,56,35]])
print(student_data)
print("student wise avg")
print(np.mean((student_data[:,1:]),axis=1))
print("top scorer")
a=(np.argmax(np.mean((student_data[:,1:]),axis=1)))
print(student_data[a,0])
print()
print("subject wise average")
print(np.mean(student_data[:,1:],axis=0))
print()
print("failed students")
print(student_data[np.mean((student_data[:,1:]),axis=1)<35])
print(np.mean((student_data[:,1:]),axis=1)<35)



[[ 1 90 80 90 80 80 99]
 [ 2 50 80 40 80 80 80]
 [ 3 50 20 90 80 40 90]
 [ 4 30 80 90 50 20 90]
 [ 5 10 40 50 20 11 70]
 [ 6 80 45 36 45 36 34]
 [ 7 66 84 45 57 26 46]
 [ 8 46 46 35 35 56 35]]
student wise avg
[86.5        68.33333333 61.66666667 60.         33.5        46.
 54.         42.16666667]
top scorer
1

subject wise average
[52.75  59.375 59.5   55.875 43.625 68.   ]

failed students
[[ 5 10 40 50 20 11 70]]
[False False False False  True False False False]


## 2. Weather Temperature Analysis

Generate random temperatures for 30 days.

Tasks:
- Find hottest and coldest day
- Find average temperature
- Find days above average
- Reshape into weekly data
- Find weekly averages


### Hints
- Use `np.random.randint()`
- Use `reshape()` for weekly grouping
- Use boolean indexing for above-average days
- `np.mean()` will help for averages


In [5]:
# Write your solution here

weather_data=np.random.randint(20,40,30)
max_temp=np.max(weather_data)
min_temp=np.min(weather_data)
avg_temp=np.mean(weather_data)
days_above_avg_temp=(weather_data>avg_temp)

print(weather_data[days_above_avg_temp])
weather_data=np.append(weather_data,[0,0,0,0,0])
weather_data=(weather_data.reshape(5,7))
weekly_avg= np.mean(weather_data[0:4,:])
print(weather_data)
print()

print(max_temp,min_temp)
print()
print(avg_temp)
print()
print(weekly_avg)
print()



[33 33 32 39 34 36 32 36 39 36 38 39 36 32 32 37 31]
[[21 33 28 28 33 27 32]
 [20 39 34 36 32 28 22]
 [22 36 39 29 21 30 36]
 [38 39 36 32 22 32 23]
 [37 31  0  0  0  0  0]]

39 20

30.533333333333335

30.285714285714285



## 3. Image Pixel Simulator

Create a random 256x256 grayscale image array.

Tasks:
- Increase brightness
- Decrease brightness
- Crop image
- Flip image horizontally
- Normalize pixel values


### Hints
- Pixel values are usually between 0–255
- Add/subtract values for brightness changes
- Use slicing for cropping
- Use `np.flip()` or slicing tricks
- Normalize using division


In [6]:
# Write your solution here
image = np.random.randint(0,255,size=(256,256))
print(image)
print("-------------------")
# increase bright ness
print(image+1)
print("-------------------")
# decrease bright ness 
print(image-1)
# cropping the image 
print("-------------------")
#cropping the image
print(image[250:,250:])
print("-------------------")
# flipping the image 
print(np.flip(image))
print("-------------------")
#normalizing the image 

print((image-np.min(image))/(np.max(image)-np.min(image)))





[[ 77  14 150 ...  74 121 104]
 [162 167 247 ...  85 228 174]
 [  4 161  43 ...  14  55 246]
 ...
 [111 115  73 ... 143  62  84]
 [159 204  67 ... 155 129 170]
 [  0 175 188 ... 122  42 171]]
-------------------
[[ 78  15 151 ...  75 122 105]
 [163 168 248 ...  86 229 175]
 [  5 162  44 ...  15  56 247]
 ...
 [112 116  74 ... 144  63  85]
 [160 205  68 ... 156 130 171]
 [  1 176 189 ... 123  43 172]]
-------------------
[[ 76  13 149 ...  73 120 103]
 [161 166 246 ...  84 227 173]
 [  3 160  42 ...  13  54 245]
 ...
 [110 114  72 ... 142  61  83]
 [158 203  66 ... 154 128 169]
 [ -1 174 187 ... 121  41 170]]
-------------------
[[168 169 197  75 107  85]
 [238 185 188 155 201  48]
 [149 210  24  43 119  45]
 [126 212 102 143  62  84]
 [231  95 242 155 129 170]
 [229  31 115 122  42 171]]
-------------------
[[171  42 122 ... 188 175   0]
 [170 129 155 ...  67 204 159]
 [ 84  62 143 ...  73 115 111]
 ...
 [246  55  14 ...  43 161   4]
 [174 228  85 ... 247 167 162]
 [104 121  74 ... 150

## 4. Sales Data Dashboard

Create monthly sales data for multiple products.

Tasks:
- Total sales
- Best-selling product
- Monthly growth
- Highest sales month
- Cumulative sales


### Hints
- Use `axis` carefully
- Use `np.sum()`
- Use `np.cumsum()`
- Use subtraction to calculate growth


In [7]:
# Write your solution here
# the data is is 10X2  product id followed by sales 
products = np.arange(100,110).reshape(10,1)
sales = np.random.randint(10,432,size=(10,12)) 
data=np.concatenate((products,sales),axis=1) # data 
# print(data)

# product total sales 

total_sales_of_product= np.sum(data[:,1:],axis=1)
best_selling_product = np.argmax(np.sum(data[:,1:],axis=1))
print(total_sales_of_product)
print(data[best_selling_product,0:1])
monthly_wise_sales= np.sum(data[:,1:],axis=0)
print()
print(monthly_wise_sales)
best_selling_month=np.argmax(np.sum(data[:,1:],axis=0))
print(best_selling_month)
print()
month_wise_cum_data= np.cumsum(data[:,1:],axis=1)
print(month_wise_cum_data)


[3189 2776 2889 2507 1867 2482 2361 2356 2420 2348]
[100]

[2163 2549 1534 1631 2688 2385 2409 2061 1897 1550 1941 2387]
4

[[  84  508  633  889 1268 1618 1976 2005 2317 2419 2791 3189]
 [ 230  580  626  772 1093 1461 1868 2202 2304 2327 2624 2776]
 [ 173  344  382  807 1234 1493 1829 2141 2392 2450 2606 2889]
 [ 322  577  805  818 1215 1607 1650 1975 2054 2211 2369 2507]
 [ 308  634  792  802 1208 1278 1398 1583 1756 1831 1855 1867]
 [ 176  398  802  916 1166 1272 1677 1820 2029 2188 2359 2482]
 [  68  257  465  835  852  956 1168 1388 1678 1740 2026 2361]
 [  74  312  393  485  724  848 1017 1295 1559 1781 2000 2356]
 [ 320  664  836  927 1168 1409 1535 1566 1588 1977 2049 2420]
 [ 408  438  512  626  637 1008 1241 1445 1640 1943 2129 2348]]


## 5. NumPy Mini Calculator

Create functions for:
- Matrix addition
- Matrix subtraction
- Matrix multiplication
- Transpose
- Determinant


### Hints
- Use `+`, `-`, `@`
- Use `.T` for transpose
- Use `np.linalg.det()`
- Remember matrix shapes must match


In [8]:
# Write your solution here
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
B= np.array([[1,1,1],[2,2,2],[3,3,3]])

print(A)
print()
print(B)

print(A+B)
print()
print(A-B)
print()
print(np.dot(A,B))
print()
print(np.transpose(A))

print()
print(np.linalg.det(A))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]

[[0 1 2]
 [2 3 4]
 [4 5 6]]

[[14 14 14]
 [32 32 32]
 [50 50 50]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

6.66133814775094e-16


## 6. Cricket Score Analyzer

Store runs scored by players across matches.

Tasks:
- Highest average
- Most consistent player
- Count 50+ scores
- Standard deviation of runs


### Hints
- Use `np.mean()`
- Use `np.std()`
- Boolean conditions help for 50+ scores
- Lower standard deviation means more consistency


In [17]:
# Write your solution here
players = np.arange(1,11).reshape(10,1)
scores = np.random.randint(1,121,(10,20))
data= np.concatenate((players,scores),axis=1)
print()
# print(data) 
print(data[np.argmax(np.mean(data[:,1:],axis=1),axis=0),:1])
# counting 50 + scores 
# print(data[:,1:][data[:,1:]>50])
print(np.sum(data[:,1:]>50,axis=1)) # 50+ scores of each player 
print(np.sum(data[:,1:]>50)) # total 50+ scores
std_dev_of_each_player=np.std(data[:,1:],axis=1)
print(data[np.argmin(std_dev_of_each_player),:1])








[1]
[15 13 13 13 14 13 13 11 14 12]
131
[10]


## 7. Recommendation System Mini Project

Create a user-movie rating matrix.

Tasks:
- Average movie rating
- Most liked movie
- Find similar users
- Recommend movies


### Hints
- Think of rows as users and columns as movies
- Use dot products for similarity
- Use averages across columns
- Broadcasting may help


In [121]:
# Write your solution here

users= np.arange(1,6).reshape(5,1)

movies=np.random.randint(0,5,30).reshape(5,6)

data=np.concatenate((users,movies),axis=1)
print(data.shape)
print()

avg_movie_rating=np.mean(data[:,1:],axis=0)
print(avg_movie_rating)
most_liked_movie = np.argmax(avg_movie_rating)
print(most_liked_movie+1) # gives most liked movie
print()

similar_users=np.array([])
print(similar_users)
print()
# related users 
for user in range(0,data.shape[0]):
    for movies in range(0,data.shape[0]):
        if(user==movies):
            continue
        a=np.dot(data[user,1:],data[movies,1:])
        similar_users=np.append(similar_users,a)


print()

similar_users=(similar_users).reshape(5,4)
print(similar_users)
print()
print()

# now we will get the list of similar users 

most_similar_users= []

print(similar_users.shape)
for i in range(0,similar_users.shape[0]):

    # find best similarity position in current row
    b = np.argmax(similar_users[i,:])

    # mapping actual user ids because self-user was skipped
    compared_users = [x for x in range(data.shape[0]) if x != i]

    # actual most similar user
    actual_user = compared_users[b]

    most_similar_users.append((i, actual_user))


# recommend movies

recommendations = []

for i in most_similar_users:

    current_user = i[0]
    similar_user = i[1]

    # current user movie ratings
    current_user_movies = data[current_user,1:]

    # similar user movie ratings
    similar_user_movies = data[similar_user,1:]

    # movies not watched by current user
    unwatched_movies = (current_user_movies == 0)

    # recommend movies liked by similar user
    recommended = np.where(
        (unwatched_movies) & (similar_user_movies >= 4)
    )[0]

    recommendations.append((current_user, recommended))

print(recommendations)

(5, 7)

[1.8 1.8 1.  1.8 2.  2.6]
6

[]


[[30. 35. 19. 18.]
 [30. 37.  9.  6.]
 [35. 37.  9.  5.]
 [19.  9.  9. 17.]
 [18.  6.  5. 17.]]


(5, 4)
[(0, array([], dtype=int64)), (1, array([], dtype=int64)), (2, array([], dtype=int64)), (3, array([], dtype=int64)), (4, array([0], dtype=int64))]


## .8. NumPy Game of Life

Create a mini Conway's Game of Life.

Tasks:
- Create grid
- Count neighbors
- Update cells
- Simulate generations


### Hints
- Use a 2D array of 0s and 1s
- Slicing helps count neighbors
- Use conditions for alive/dead logic
- You may need nested loops initially


In [85]:
# Write your solution here


## 9. Fraud Detection Simulation

Generate transaction data.

Tasks:
- Detect abnormal transactions
- Find outliers using z-score
- Filter suspicious transactions


### Hints
- Use mean and standard deviation
- Z-score formula:
  z = (x - mean) / std
- Large absolute z-scores may indicate fraud


In [12]:
# Write your solution here


## 10. Mini Neural Network Forward Pass

Create:
- Input matrix
- Weight matrix
- Bias vector

Perform:
- Matrix multiplication
- Activation function
- Prediction output


### Hints
- Use `@` or `np.dot()`
- Use broadcasting for bias addition
- Try ReLU:
  `np.maximum(0, x)`
- Shape matching is very important


In [13]:
# Write your solution here
