Numpy : Numerical python 



In [2]:
# create a numpy array
import numpy as np

a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
import timeit # to accurately measure the execution time of small code snippets 

a="5+5"
print(a)
print(timeit.timeit(a))

t1=timeit.default_timer()
a=1-23-4-5-6-34-23-354-64-63-3-4-45
t2=timeit.default_timer()
print(t2-t1)




5+5
0.010005999996792525
8.100000195554458e-05


In [15]:
%timeit 5+5

8.85 ns ± 0.364 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [23]:
# different dimension arrays
oneD=np.array([1,2,3,4,5])
twoD=np.array([[1,2,3],[4,5,6]])
threeD=np.array([[[1,2],[2,3],[4,5]]])
print(oneD)
print(oneD.ndim)
print(twoD)
print(twoD.ndim)
print(threeD)
print(threeD.ndim)

[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2]
  [2 3]
  [4 5]]]
3


In [26]:
# array filled with zeros
zeros_1D=np.zeros(4)
print(zeros_1)

[0. 0. 0. 0.]


In [27]:
zeros_2D=np.zeros((3,4))
print(zeros_2D)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
#arrays filled with one 
ones_1D=np.ones(4)
print(ones_1D)

[1. 1. 1. 1.]


In [30]:
ones_2d=np.ones((3,4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
empty_2d=np.empty((3,4))
print(empty_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
# fill elements 

arange_1=np.arange(4)
print(arange_1)


[0 1 2 3]


In [35]:
arange_2=np.arange(3,8)
print(arange_2)

[3 4 5 6 7]


In [37]:
# array with diagonal elements 

diagonal_1=np.eye(3)
print(diagonal_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
diagonal_2=np.eye(3,5)
print(diagonal_2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [40]:
#evenly spaced array

ar_lin=np.linspace(0,10,5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# creating array with random elements


In [43]:
print(np.random.ranf((2,2)))

[[0.55733359 0.63218193]
 [0.64336162 0.38428268]]


In [45]:
print(np.random.rand(2,2))

[[0.25689318 0.53726187]
 [0.46765925 0.80971197]]


In [51]:
print(np.random.randint(0,10,size=(4,4)))

[[1 6 0 8]
 [8 3 2 7]
 [2 7 2 5]
 [5 3 6 1]]


# Datatypes

In [55]:
arr=np.array([1,2,3,4,5])

print(arr.dtype)

int32


In [61]:
print(arr.astype(np.float64)) #change numpy array datatype

[1. 2. 3. 4. 5.]


# changing numpy array shape


In [65]:
arr=np.random.randint(0,6,size=6)
print(arr)

[2 1 2 0 5 5]


In [70]:
print(arr)

[2 1 2 0 5 5]


In [81]:
brr=np.array([1,2,3,4],ndmin=2)
print(brr.shape)
print()
print(brr.reshape(2,2)) # change shape of the array 
print()
print(brr.shape)


(1, 4)

[[1 2]
 [3 4]]

(1, 4)


In [83]:
crr=np.array([1,2,3,4,5,6])
print(crr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


# numpy arthematic operations

In [87]:

a=np.array([1,2,3])
b=np.array([3,3,3])




print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))
print(np.reciprocal(a))


[4 5 6]
[-2 -1  0]
[3 6 9]
[0.33333333 0.66666667 1.        ]
[1 2 0]
[ 1  8 27]
[1 0 0]


In [88]:
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.cumsum(a))

1
3
0
2
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


## BroadCasting


In [97]:
u=np.array([1,2,3,4])
v=np.array([[1],[2],[3],[4]])
print(u)
print(u.shape)

print()
print(v)
print(v.shape)

[1 2 3 4]
(4,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [98]:
print(u+v)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [99]:
print(u*v)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


## iterating

In [100]:
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a)



[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [106]:
for i,d in np.ndenumerate(a):
    print(i,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 6
(2, 1) 7
(2, 2) 8


## copy vs view


In [108]:
a=np.array([1,2,3,4])
b=a.copy()
c=a.view()
print(a,b,c)




[1 2 3 4] [1 2 3 4] [1 2 3 4]


## join and split


In [116]:
a=np.array([1,2,3,4])
b=np.array([1,1,1,1])

print(np.concatenate((a,b),axis=0))


[1 2 3 4 1 1 1 1]


# Stack


In [120]:
a=np.array([1,2,3,4])
b=np.array([1,1,1,1])
print(np.stack((a,b),axis=0))

[[1 2 3 4]
 [1 1 1 1]]


# search / sort /filter


In [122]:
a=np.array([1,2,3,4])
print(np.where(a==2))

(array([1], dtype=int64),)


In [124]:
print(np.searchsorted(a,2,side='right'))

2


In [126]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[a>4])

[5 6 7 8 9]


In [127]:
print(a>2)


[False False  True  True  True  True  True  True  True]


In [128]:
a=np.array([[1,2],[2,3],[3,4]])
print(a.flatten())

[1 2 2 3 3 4]


# insert 


In [129]:
a=np.array([1,2,3,4,5,6])


In [131]:
a=np.insert(a,0,0)
print(a)

[0 1 2 3 4 5 6]


In [143]:
b=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(b)
print()
print(np.insert(b,3,[4,4,4],axis=1)) 

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


# matrices


In [149]:
a=np.matrix([[1,0,3],[2,1,4],[3,2,5]])
print(a)


[[1 0 3]
 [2 1 4]
 [3 2 5]]


In [150]:
print(np.swapaxes(a,0,1))

[[1 2 3]
 [0 1 2]
 [3 4 5]]


In [151]:
print(np.transpose(a))



[[1 2 3]
 [0 1 2]
 [3 4 5]]
