In [3]:
import numpy as np

# creating a numpy array


In [4]:

x=[1,2,3,4]
y=np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
l=[]
for i in range(1,5):
    # int_l=input("enter: ")
    # l.append(int(int_l))
    pass
print(l)

[]


# Dimensions in array 
1-D = [1,2,3,4]
2-D= [[1,2,3,4]]
3-D= [[[1,2,3,4]]]
Higher Dimensional Arrays 

In [6]:
print(y.ndim)

1


In [7]:
# CREATING 2 d array 

ar2=np.array([[1,2,3],[4,5,6]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
#creating a 3d array


arr3= np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [9]:
#creating n dimension array

arrn=np.array([1,2,3,4],ndmin=10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [10]:
#CREATING A  zero array

ar_zero=np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


# Creating a different types of arrays using numpys


In [11]:
#creating an array
a_array=np.array([1,2,3,4])
print(a_array)

[1 2 3 4]


In [12]:
#creating arrays with zeros

a_zeros=np.zeros(4)
print(a_zeros)

[0. 0. 0. 0.]


In [13]:
a_zeros_1=np.zeros((3,4))
print(a_zeros_1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# creating arrays with one 

a_ones= np.ones(4)
print(a_ones)


[1. 1. 1. 1.]


In [15]:
a_ones_1=np.ones((3,4))
print(a_ones_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# printing empty array but if we use this the we will get last saved values in the memory 
a_empty=np.empty(4)
print(a_empty)

[1. 1. 1. 1.]


In [17]:
arr_arange=np.arange(4)
print(arr_arange)


[0 1 2 3]


In [18]:
arr_arange_1=np.arange(3,4)
print(arr_arange_1)

[3]


In [19]:
#creating a diagonal array
arr_dia=np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
arr_dia_1=np.eye(5,5)
print(arr_dia_1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# GENERATING ARRAY WITH RANDOM VALUES


In [21]:
arr_rand=np.random.rand(5)
print(arr_rand)

[0.90195705 0.6028172  0.05959619 0.84299881 0.28899369]


In [22]:
arr_ranf=np.random.ranf((2,6))
print(arr_ranf)

[[0.93617017 0.83974749 0.1121166  0.12687381 0.65874546 0.44724382]
 [0.87803495 0.2777581  0.27182327 0.11020086 0.10122671 0.93069597]]


In [23]:
arr_randint=np.random.randint(0,5,2)
print(arr_randint)

[4 3]


# DataType


In [24]:
var = np.array([1,2,3,4])
print(var)

[1 2 3 4]


In [25]:
print("DataType: ",var.dtype)

DataType:  int32


In [26]:

var_1= np.array(var,dtype="float")
var_2=np.array(var,dtype='U')
var_3=var_2.astype("int")

In [27]:

print(var_1)
print(var_2)
print(var_3)

[1. 2. 3. 4.]
['1' '2' '3' '4']
[1 2 3 4]


In [28]:
print(var_1.dtype)

float64


# Shape and Reshape


In [29]:
a=np.array([1,2,3,4])
print(a.ndim)
print(a.shape)
b=a.reshape(2,2)
print(b.ndim)
print(b.shape)

1
(4,)
2
(2, 2)


In [30]:
#multidimensional array

b=np.array([1,2,3,4],ndmin=4)
print(b)


[[[[1 2 3 4]]]]


# Arthematic Operations

In [31]:
a=np.array([1,2,3])
b=np.array([2,2,2])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))
print(np.reciprocal(a))


[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 0 1]
[1 4 9]
[1 0 0]


In [32]:
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(b))
print(np.cumsum(a))

1
3
0
2
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[-0.41614684 -0.41614684 -0.41614684]
[1 3 6]


# min max on 2d arrays

In [33]:
a=[[1,2,3],[0,3,4]]


print(np.min(a,axis=0))







[0 2 3]


In [34]:
print(np.min(a,axis=1))

[1 0]


In [35]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
b=np.array([1,2,3,4,5])
b=b.reshape(5,1)

a=a.reshape(5,3)


print(a+b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [36]:
c=a.ravel()

In [37]:
print(c.shape)

(15,)


# BroadCasting


In [38]:
a=np.array([1,2,3])
print(a,a.shape)
b=np.array([[2],[3],[4]])
print(b,b.shape)


[1 2 3] (3,)
[[2]
 [3]
 [4]] (3, 1)


In [40]:
print(a+b,(a+b).shape)

[[3 4 5]
 [4 5 6]
 [5 6 7]] (3, 3)


In [44]:

a=np.array([1,2,3,4,5,6])
b=np.array([[2],[3],[4]])
print(a)
print(b)
print(a.shape,b.shape)
print(a+b)
print((a+b).shape)





[1 2 3 4 5 6]
[[2]
 [3]
 [4]]
(6,) (3, 1)
[[ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]
(3, 6)


# indexing and slicing 


In [46]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [47]:
b=[[1,2,3],[4,5,6]]
print(b)

[[1, 2, 3], [4, 5, 6]]


In [50]:
print(b[1][0:])

[4, 5, 6]


In [53]:
#indexing on 3d array 

a=np.array([[[1,2,3],[4,5,6]]])
print(a)
print()
print(a.shape)

[[[1 2 3]
  [4 5 6]]]

(1, 2, 3)


In [63]:
print(a[0][1][-3:])

[4 5 6]


# iterating in Numpy


In [64]:
a=np.array([1,2,3,4,5,6,7,8])
for i in a:
    print(i)

1
2
3
4
5
6
7
8


In [66]:
b=np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(b,flags=['buffered'],op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
