Numpy : Numerical python 



In [2]:
# create a numpy array
import numpy as np

a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
import timeit # to accurately measure the execution time of small code snippets 

a="5+5"
print(a)
print(timeit.timeit(a))

t1=timeit.default_timer()
a=1-23-4-5-6-34-23-354-64-63-3-4-45
t2=timeit.default_timer()
print(t2-t1)




5+5
0.010005999996792525
8.100000195554458e-05


In [15]:
%timeit 5+5

8.85 ns ± 0.364 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [23]:
# different dimension arrays
oneD=np.array([1,2,3,4,5])
twoD=np.array([[1,2,3],[4,5,6]])
threeD=np.array([[[1,2],[2,3],[4,5]]])
print(oneD)
print(oneD.ndim)
print(twoD)
print(twoD.ndim)
print(threeD)
print(threeD.ndim)

[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2]
  [2 3]
  [4 5]]]
3


In [26]:
# array filled with zeros
zeros_1D=np.zeros(4)
print(zeros_1)

[0. 0. 0. 0.]


In [27]:
zeros_2D=np.zeros((3,4))
print(zeros_2D)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
#arrays filled with one 
ones_1D=np.ones(4)
print(ones_1D)

[1. 1. 1. 1.]


In [30]:
ones_2d=np.ones((3,4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
empty_2d=np.empty((3,4))
print(empty_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
# fill elements 

arange_1=np.arange(4)
print(arange_1)


[0 1 2 3]


In [35]:
arange_2=np.arange(3,8)
print(arange_2)

[3 4 5 6 7]


In [37]:
# array with diagonal elements 

diagonal_1=np.eye(3)
print(diagonal_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
diagonal_2=np.eye(3,5)
print(diagonal_2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [40]:
#evenly spaced array

ar_lin=np.linspace(0,10,5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# creating array with random elements


In [43]:
print(np.random.ranf((2,2)))

[[0.55733359 0.63218193]
 [0.64336162 0.38428268]]


In [45]:
print(np.random.rand(2,2))

[[0.25689318 0.53726187]
 [0.46765925 0.80971197]]


In [51]:
print(np.random.randint(0,10,size=(4,4)))

[[1 6 0 8]
 [8 3 2 7]
 [2 7 2 5]
 [5 3 6 1]]


# Datatypes